spring:
  application:
    name: phiz-gateway

server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

client:
  user:
    url: http://localhost:7001/user
    name: user-service
  otp:
    url: http://localhost:7002/otp
    name: otp-service

jwt:
  secret: phiz_secret


